#!/bin/sh
# This file is part of Crag.
#
# Copyright (C) 2026 Ralf Claussnitzer
#
# Crag is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# Crag is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Crag. If not, see <https://www.gnu.org/licenses/>.

# Runs cargo inside the pinned toolchain image (see Dockerfile).
# Usage: ./cargo build, ./cargo test, ./cargo clippy, ...
set -eu
root=$(cd "$(dirname "$0")" && pwd)
image=crag-dev
docker image inspect "$image" >/dev/null 2>&1 || docker build -q -t "$image" "$root" >/dev/null
mkdir -p "$root/.cargo-home"
tty=; [ -t 0 ] && [ -t 1 ] && tty=-it
exec docker run --rm $tty \
  --user "$(id -u):$(id -g)" \
  -v "$root:$root" -w "$PWD" \
  -e CARGO_HOME="$root/.cargo-home" \
  "$image" cargo "$@"
