[package]
name = "crag-codegen"
description = "Crag code generation: the facade over Cranelift"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
crag-abi = { path = "../crag-abi" }
cranelift-codegen = "0.136.2"
cranelift-frontend = "0.136.2"
target-lexicon = "0.13.5"

[dev-dependencies]
crag-loader = { path = "../crag-loader" }
