[package]
name = "crag-runtime"
description = "Crag runtime: fibers, growable stacks, side stack, allocator, reference counting, lists and maps, traps"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
libc = "0.2.190"
crag-abi = { path = "../crag-abi" }

[dev-dependencies]
crag-codegen = { path = "../crag-codegen" }
crag-loader = { path = "../crag-loader" }
