[package]
name = "crag-loader"
description = "Crag code loader: maps code objects into executable memory"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
crag-abi = { path = "../crag-abi" }
libc = "0.2.190"
